{
 "title": "PostgreSQL Exporter Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total DB Size (postgres)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Tuples Fetched",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Tuples Inserted",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Transactions Committed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Tuples Returned vs Fetched",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Tuples Updated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Tuples Deleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname=\"postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Temp Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_files{datname=\"postgres\"}[5m])"
    }
   ]
  }
 ]
}